export const globalLenses = [
  "Memory",
  "Identity",
  "Obsession",
  "Reality vs Illusion",
  "Control",
  "Freedom",
  "Isolation",
  "Guilt",
  "Performance",
  "Violence",
  "Justice",
  "Trauma",
] as const;

export type GlobalLens = (typeof globalLenses)[number];

export const films = [
  {
    slug: "shawshank-redemption",
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    lenses: ["Freedom", "Justice", "Control"],
    specificAngles: ["Hope", "Institutional Control", "Friendship"],
  },
  {
    slug: "fight-club",
    title: "Fight Club",
    year: 1999,
    director: "David Fincher",
    lenses: ["Identity", "Violence", "Obsession"],
    specificAngles: ["Masculinity", "Consumerism", "Doubles"],
  },
  {
    slug: "one-flew-over-the-cuckoos-nest",
    title: "One Flew Over the Cuckoo's Nest",
    year: 1975,
    director: "Milos Forman",
    lenses: ["Control", "Freedom", "Identity"],
    specificAngles: ["Institutional Power", "Rebellion", "Madness"],
  },
  {
    slug: "se7en",
    title: "Se7en",
    year: 1995,
    director: "David Fincher",
    lenses: ["Justice", "Violence", "Obsession", "Guilt"],
    specificAngles: ["Moral Decay", "Punishment"],
  },
  {
    slug: "silence-of-the-lambs",
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    lenses: ["Identity", "Control", "Violence"],
    specificAngles: ["Power", "Fear", "Gender"],
  },
  {
    slug: "the-prestige",
    title: "The Prestige",
    year: 2006,
    director: "Christopher Nolan",
    lenses: ["Obsession", "Performance", "Identity"],
    specificAngles: ["Sacrifice", "Doubles", "Truth"],
  },
  {
    slug: "memento",
    title: "Memento",
    year: 2000,
    director: "Christopher Nolan",
    lenses: ["Memory", "Identity", "Guilt", "Reality vs Illusion"],
    specificAngles: ["Truth", "Self-Deception"],
  },
  {
    slug: "taxi-driver",
    title: "Taxi Driver",
    year: 1976,
    director: "Martin Scorsese",
    lenses: ["Isolation", "Violence", "Identity"],
    specificAngles: ["Masculinity", "Alienation", "Moral Delusion"],
  },
  {
    slug: "shutter-island",
    title: "Shutter Island",
    year: 2010,
    director: "Martin Scorsese",
    lenses: ["Reality vs Illusion", "Trauma", "Guilt"],
    specificAngles: ["Denial", "Madness"],
  },
  {
    slug: "black-swan",
    title: "Black Swan",
    year: 2010,
    director: "Darren Aronofsky",
    lenses: ["Performance", "Identity", "Obsession", "Control"],
    specificAngles: ["Doubles", "Perfection"],
  },
  {
    slug: "sixth-sense",
    title: "The Sixth Sense",
    year: 1999,
    director: "M. Night Shyamalan",
    lenses: ["Trauma", "Reality vs Illusion", "Isolation"],
    specificAngles: ["Grief", "Perception", "Childhood", "Revelation"],
  },
  {
    slug: "prisoners",
    title: "Prisoners",
    year: 2013,
    director: "Denis Villeneuve",
    lenses: ["Justice", "Violence", "Obsession", "Guilt"],
    specificAngles: ["Faith", "Moral Ambiguity"],
  },
  {
    slug: "gone-girl",
    title: "Gone Girl",
    year: 2014,
    director: "David Fincher",
    lenses: ["Performance", "Identity", "Control"],
    specificAngles: ["Marriage", "Media", "Manipulation"],
  },
  {
    slug: "requiem-for-a-dream",
    title: "Requiem for a Dream",
    year: 2000,
    director: "Darren Aronofsky",
    lenses: ["Obsession", "Control", "Trauma"],
    specificAngles: ["Addiction", "Desire", "Decay", "Body"],
  },
  {
    slug: "donnie-darko",
    title: "Donnie Darko",
    year: 2001,
    director: "Richard Kelly",
    lenses: ["Reality vs Illusion", "Isolation", "Trauma"],
    specificAngles: ["Time", "Fate", "Madness"],
  },
  {
    slug: "the-machinist",
    title: "The Machinist",
    year: 2004,
    director: "Brad Anderson",
    lenses: ["Guilt", "Trauma", "Identity"],
    specificAngles: ["Insomnia", "Body", "Self-Punishment"],
  },
  {
    slug: "mulholland-drive",
    title: "Mulholland Drive",
    year: 2001,
    director: "David Lynch",
    lenses: ["Reality vs Illusion", "Identity", "Obsession", "Performance"],
    specificAngles: ["Dream Logic", "Desire", "Hollywood"],
  },
  {
    slug: "truman-show",
    title: "The Truman Show",
    year: 1998,
    director: "Peter Weir",
    lenses: ["Control", "Freedom", "Reality vs Illusion", "Performance"],
    specificAngles: ["Surveillance", "Media", "Authorship"],
  },
] as const;
